# -*- coding: utf-8 -*-
"""Institutional Data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z3zjyWTJ0FqEXKbv-C-mZ_z7ymPSu57C
"""

import pandas as pd
import os
import requests

os.system('cls')

token = input("Enter API token")
# for example: 87bdd83a2fb5811afe7800c8db6d4e9235b16bce

site = input("Enter the Tab URL")
# for example: https://iimapd24.calicotab.com/

x=0

sheet = pd.read_excel(open('database.xlsx', 'rb'),
                      sheet_name='Institutions')

for k in sheet['Long']:

    a = sheet['Long'][x]
    b = sheet['Short'][x]
    x = x+1

    r = requests.post(
        f'{site}api/v1/institutions',
        json = {
                    "name": a,
                    "code": b,
                },
        headers={
                'Authorization': 'token '+token
                })
    status = r.status_code
    if status != 201:
        print("Error occured while posting {a}, {b}\n Error {status}\n{r.text}")

print("SUCCESS! Post completed")

